version: "3.4"
services:
  sonarr:
    image: linuxserver/sonarr
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    network_mode: host
    volumes:
      - type: bind
        source: "${DATA}/media/config/sonarr"
        target: /config
      - type: bind
        source: "${DATA}/media/tv"
        target: /tv
      - type: bind
        source: "${DATA}/media/downloads"
        target: /downloads

  radarr:
    image: linuxserver/radarr
    network_mode: host
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - type: bind
        source: "${DATA}/media/config/radarr"
        target: /config
      - type: bind
        source: "${DATA}/media/movies"
        target: /movies
      - type: bind
        source: "${DATA}/media/downloads"
        target: /downloads

  transmission:
    image: linuxserver/transmission
    network_mode: host
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - type: bind
        source: "${DATA}/media/config/transmission"
        target: /config
      - type: bind
        source: "${DATA}/media/watch_torrents"
        target: /watch
      - type: bind
        source: "${DATA}/media/downloads"
        target: /downloads

  jackett:
    image: linuxserver/jackett
    network_mode: host
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - type: bind
        source: "${DATA}/media/config/jackett"
        target: /config
      - type: bind
        source: "${DATA}/media/downloads"
        target: /downloads

  plex:
    image: plexinc/pms-docker
    network_mode: host
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
      - VERSION=latest
    volumes:
      - type: bind
        source: "${DATA}/media/config/plex"
        target: /config
      - type: bind
        source: "${DATA}/media/downloads"
        target: /downloads
      - type: bind
        source: "${DATA}/media/tv"
        target: /tv
      - type: bind
        source: "${DATA}/media/movies"
        target: /movies
      - type: bind
        source: "${DATA}/media/plex_transcode"
        target: /transcode
